[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version = "0.6.0"
tag_format = "v$version"
change_type_map = { feat = "âœ¨ Features", fix = "ğŸ› Bug Fixes", refactor = "ğŸ”¨ Refactor", perf = "âš¡ï¸ Performance", ci = "ğŸ›  CI", test = "ğŸš¦ Tests" }

[tool.black]
line-length = 127
exclude = '(\.eggs|\.git|\.hg|\.mypy_cache|\.tox|\.venv|build|dist)'
